IG_SESSION_FILEPATH_DEFAULT = "/data/session.json"
POSTS_DEFAULT = True
POSTS_LIMIT_DEFAULT = 5
REELS_DEFAULT = True
REELS_LIMIT_DEFAULT = 3
STORIES_DEFAULT = True
TAGGED_DEFAULT = False
TAGGED_LIMIT_DEFAULT = 2
